### ISSUE TITLE
Add user to project via REST is bugged.

### ISSUE THREAD

**Issue by luddoro** [te4umea2019/CHKM8#137]
Tried to add user to project via Swagger  & the REST api. It returns an error saying a project does not exist even though it does.

**Comment by Abborren** [comment]
# Fixed but still bugged

Issue when you've been added to a project a database entry is not created which causes the following trace stack

```
(node:1944) UnhandledPromiseRejectionWarning: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list'
    at Query.Sequence._packetToError (C:\Code\school\CHKM8\src\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Code\school\CHKM8\src\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\Code\school\CHKM8\src\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Code\school\CHKM8\src\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Code\school\CHKM8\src\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Code\school\CHKM8\src\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Code\school\CHKM8\src\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\Code\school\CHKM8\src\node_modules\mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    --------------------
    at Protocol._enqueue (C:\Code\school\CHKM8\src\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Code\school\CHKM8\src\node_modules\mysql\lib\Connection.js:201:25)
    at Promise (C:\Code\school\CHKM8\src\Database.js:33:17)
    at new Promise (<anonymous>)
    at Database.query (C:\Code\school\CHKM8\src\Database.js:32:16)
    at Check.insert_check (C:\Code\school\CHKM8\src\Check.js:46:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.  

```
